# Site settings
title: Artist Management A&R
description: Premier Artist Management and A&R Services | Talent Discovery | Career Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:title.html

# Exclude files from processing
exclude:
  - README.md
  - LICENSE.txt
